---
title: "MSwM包的研究笔记"
output: html_notebook
date: "2017/07/11"
author: "autuanliu"
---
回归分析是统计学的的核心

回归：用一个或者多个预测变量（自变量或解释变量）来预测响应变量（因变量，效标变量或结果变量）的方法

回归分析可以用来挑选与响应变量相关的解释变量，可以描述两者之间的关系，也可以生成一个等式，通过解释变量来预测响应变量

相对重要的问题：模型的所有预测变量中，哪个最重要，哪个第二重要，哪个最无关紧要

R 中做回归分析的函数已经超过205个

## 回归分析的多种形式
回归类型 | 用途
--- | --- 
简单线性 | 用一个量化的解释变量预测一个量化的响应变量 
多项式 | 用一个量化的解释变量预测一个量化的响应变量，多项式型
多层 | 用拥有层级关系的数据预测一个响应变量
多元线性 | 用多个量化的解释变量预测一个量化的响应变量
多变量 | 用一个或多个的解释变量预测一个量化的响应变量 
Logistic | 预测一个类别型响应变量
泊松 | 预测代表频数的响应变量
Cox比例风险 | 预测一个事件（死亡，失败，旧病复发）发生的时间
时间序列 | 对误差项相关的时间序列建模
非线性 | 用一个量化或多个的解释变量预测一个量化的响应变量
非参数 | 模型的形式源自于数据形式，不事先设定
稳健 | 用一个或多个量化的解释变量预测一个量化的响应变量，能抵御干扰

## 普通最小二乘回归法 OLS
OLS回归是通过预测变量的加权和来预测量化的因变量，其中权重是通过数据估计而得的参数
## 用`lm()`来拟合回归模型
`y～x1+x2+...

* 符号说明
符号 | 用途
--- | ---
～ | 分隔符，左边为响应变量，右边为解释变量
+ | 分割预测变量
： | 表示预测变量的交互项（交叉乘积）y~x+z+x:z
* |  表示所有可能交互项 y~x*z*w为y~x+z+w+x:z+x:w+z:w+x:z:w
^ | 表示交互项达到某个次数y~(x+z+w)^2=y~x+z+w+x:z+x:w+z:w
. | 表示除因变量外的所有变量，y~.=y~x+z+w
- | 表示从等式中移除某个项
-1 | 删除截距项
function | 可以在表达式中使用函数 ，log(y)~x+z+w

* 其他函数
函数 | 作用
--- | ---
summary() |
coefficients() | 列出模型参数，截距和斜率
confint() | 提供模型参数的置信区间
fitted() | 列出拟合模型的预测值
residuals() | 列出模型的残差值
anova() | 生成模型的方差分析表
vcov() | 列出模型的协方差矩阵
AIC() | 
plot() | 生成评价拟合模型的诊断图
predict() | 预测响应变量

## 简单线性回归
