#!/bin/bash
# send data to the table in the MySQL database

MYSQL=$(which mysql)

if [ $# -ne 4 ]
then
 echo "Usage: mtest3 empid lastname firstname salary"
else
 statement="INSERT INTO employees VALUES ($1, '$2', '$3', $4)"
 $MYSQL test -u test << EOF
 $statement
EOF
 if [ $? -eq 0 ]
 then
    echo Data successfully added
 else
    echo Problem adding data
 fi
fi
